//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCC.DAL.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public System.Guid idcliente { get; set; }
        public string nombre { get; set; }
        public string secretkey { get; set; }
        public string apikey { get; set; }
        public int estado { get; set; }
        public System.DateTime fechareg { get; set; }
        public System.DateTime fechamod { get; set; }
    }
}
