//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCC.DAL.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class couriesconfig
    {
        public int idconfig { get; set; }
        public int idcouries { get; set; }
        public string clave { get; set; }
        public string valor { get; set; }
        public int estado { get; set; }
        public System.DateTime fechareg { get; set; }
        public System.DateTime fechamod { get; set; }
    
        public virtual couries couries { get; set; }
    }
}
